//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.25 at 03:35:00 PM BST 
//


package event_logging._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AlertTypeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AlertTypeSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Vulnerability"/>
 *     &lt;enumeration value="IDS"/>
 *     &lt;enumeration value="Malware"/>
 *     &lt;enumeration value="Network"/>
 *     &lt;enumeration value="Change"/>
 *     &lt;enumeration value="Error"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AlertTypeSimpleType")
@XmlEnum
public enum AlertTypeSimpleType {

    @XmlEnumValue("Vulnerability")
    VULNERABILITY("Vulnerability"),
    IDS("IDS"),
    @XmlEnumValue("Malware")
    MALWARE("Malware"),
    @XmlEnumValue("Network")
    NETWORK("Network"),
    @XmlEnumValue("Change")
    CHANGE("Change"),
    @XmlEnumValue("Error")
    ERROR("Error"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    AlertTypeSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AlertTypeSimpleType fromValue(String v) {
        for (AlertTypeSimpleType c: AlertTypeSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
