//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.25 at 03:35:00 PM BST 
//


package event_logging._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ApprovalComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApprovalComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Action" type="{event-logging:3}ApprovalActionSimpleType"/>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Subject" type="{event-logging:3}MultiObjectComplexType" minOccurs="0"/>
 *         &lt;element name="Requestors" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Requestor" type="{event-logging:3}UserComplexType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Approvers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Approver" type="{event-logging:3}UserComplexType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Reason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Outcome" type="{event-logging:3}OutcomeComplexType" minOccurs="0"/>
 *         &lt;element name="Data" type="{event-logging:3}DataComplexType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApprovalComplexType", propOrder = {
    "action",
    "id",
    "subject",
    "requestors",
    "approvers",
    "reason",
    "outcome",
    "data"
})
public class ApprovalComplexType {

    @XmlElement(name = "Action", required = true)
    @XmlSchemaType(name = "string")
    protected ApprovalActionSimpleType action;
    @XmlElement(name = "Id")
    protected String id;
    @XmlElement(name = "Subject")
    protected MultiObjectComplexType subject;
    @XmlElement(name = "Requestors")
    protected ApprovalComplexType.Requestors requestors;
    @XmlElement(name = "Approvers")
    protected ApprovalComplexType.Approvers approvers;
    @XmlElement(name = "Reason")
    protected String reason;
    @XmlElement(name = "Outcome")
    protected OutcomeComplexType outcome;
    @XmlElement(name = "Data")
    protected List<DataComplexType> data;

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ApprovalActionSimpleType }
     *     
     */
    public ApprovalActionSimpleType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApprovalActionSimpleType }
     *     
     */
    public void setAction(ApprovalActionSimpleType value) {
        this.action = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link MultiObjectComplexType }
     *     
     */
    public MultiObjectComplexType getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiObjectComplexType }
     *     
     */
    public void setSubject(MultiObjectComplexType value) {
        this.subject = value;
    }

    /**
     * Gets the value of the requestors property.
     * 
     * @return
     *     possible object is
     *     {@link ApprovalComplexType.Requestors }
     *     
     */
    public ApprovalComplexType.Requestors getRequestors() {
        return requestors;
    }

    /**
     * Sets the value of the requestors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApprovalComplexType.Requestors }
     *     
     */
    public void setRequestors(ApprovalComplexType.Requestors value) {
        this.requestors = value;
    }

    /**
     * Gets the value of the approvers property.
     * 
     * @return
     *     possible object is
     *     {@link ApprovalComplexType.Approvers }
     *     
     */
    public ApprovalComplexType.Approvers getApprovers() {
        return approvers;
    }

    /**
     * Sets the value of the approvers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApprovalComplexType.Approvers }
     *     
     */
    public void setApprovers(ApprovalComplexType.Approvers value) {
        this.approvers = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReason(String value) {
        this.reason = value;
    }

    /**
     * Gets the value of the outcome property.
     * 
     * @return
     *     possible object is
     *     {@link OutcomeComplexType }
     *     
     */
    public OutcomeComplexType getOutcome() {
        return outcome;
    }

    /**
     * Sets the value of the outcome property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutcomeComplexType }
     *     
     */
    public void setOutcome(OutcomeComplexType value) {
        this.outcome = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the data property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataComplexType }
     * 
     * 
     */
    public List<DataComplexType> getData() {
        if (data == null) {
            data = new ArrayList<DataComplexType>();
        }
        return this.data;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Approver" type="{event-logging:3}UserComplexType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "approver"
    })
    public static class Approvers {

        @XmlElement(name = "Approver", required = true)
        protected List<UserComplexType> approver;

        /**
         * Gets the value of the approver property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the approver property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getApprover().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UserComplexType }
         * 
         * 
         */
        public List<UserComplexType> getApprover() {
            if (approver == null) {
                approver = new ArrayList<UserComplexType>();
            }
            return this.approver;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Requestor" type="{event-logging:3}UserComplexType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "requestor"
    })
    public static class Requestors {

        @XmlElement(name = "Requestor", required = true)
        protected List<UserComplexType> requestor;

        /**
         * Gets the value of the requestor property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the requestor property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRequestor().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UserComplexType }
         * 
         * 
         */
        public List<UserComplexType> getRequestor() {
            if (requestor == null) {
                requestor = new ArrayList<UserComplexType>();
            }
            return this.requestor;
        }

    }

}
