//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.25 at 03:35:00 PM BST 
//


package event_logging._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AuthenticateActionSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AuthenticateActionSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Logon"/>
 *     &lt;enumeration value="Logoff"/>
 *     &lt;enumeration value="ChangePassword"/>
 *     &lt;enumeration value="ResetPassword"/>
 *     &lt;enumeration value="ScreenLock"/>
 *     &lt;enumeration value="ScreenUnlock"/>
 *     &lt;enumeration value="AccountLock"/>
 *     &lt;enumeration value="AccountUnlock"/>
 *     &lt;enumeration value="Reconnect"/>
 *     &lt;enumeration value="Disconnect"/>
 *     &lt;enumeration value="Connect"/>
 *     &lt;enumeration value="ElevatePrivilege"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AuthenticateActionSimpleType")
@XmlEnum
public enum AuthenticateActionSimpleType {

    @XmlEnumValue("Logon")
    LOGON("Logon"),
    @XmlEnumValue("Logoff")
    LOGOFF("Logoff"),
    @XmlEnumValue("ChangePassword")
    CHANGE_PASSWORD("ChangePassword"),
    @XmlEnumValue("ResetPassword")
    RESET_PASSWORD("ResetPassword"),
    @XmlEnumValue("ScreenLock")
    SCREEN_LOCK("ScreenLock"),
    @XmlEnumValue("ScreenUnlock")
    SCREEN_UNLOCK("ScreenUnlock"),
    @XmlEnumValue("AccountLock")
    ACCOUNT_LOCK("AccountLock"),
    @XmlEnumValue("AccountUnlock")
    ACCOUNT_UNLOCK("AccountUnlock"),
    @XmlEnumValue("Reconnect")
    RECONNECT("Reconnect"),
    @XmlEnumValue("Disconnect")
    DISCONNECT("Disconnect"),
    @XmlEnumValue("Connect")
    CONNECT("Connect"),
    @XmlEnumValue("ElevatePrivilege")
    ELEVATE_PRIVILEGE("ElevatePrivilege"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    AuthenticateActionSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AuthenticateActionSimpleType fromValue(String v) {
        for (AuthenticateActionSimpleType c: AuthenticateActionSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
