//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.25 at 03:35:00 PM BST 
//


package event_logging._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseNetworkComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseNetworkComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Source" type="{event-logging:3}NetworkSrcDstComplexType"/>
 *         &lt;element name="Destination" type="{event-logging:3}NetworkSrcDstComplexType" minOccurs="0"/>
 *         &lt;element name="ProcessName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Payload" type="{event-logging:3}MultiObjectComplexType" minOccurs="0"/>
 *         &lt;element name="Rule" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseNetworkComplexType", propOrder = {
    "source",
    "destination",
    "processName",
    "payload",
    "rule"
})
@XmlSeeAlso({
    NetworkOutcomeComplexType.class,
    NetworkComplexType.class
})
public abstract class BaseNetworkComplexType {

    @XmlElement(name = "Source", required = true)
    protected NetworkSrcDstComplexType source;
    @XmlElement(name = "Destination")
    protected NetworkSrcDstComplexType destination;
    @XmlElement(name = "ProcessName")
    protected String processName;
    @XmlElement(name = "Payload")
    protected MultiObjectComplexType payload;
    @XmlElement(name = "Rule")
    protected String rule;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkSrcDstComplexType }
     *     
     */
    public NetworkSrcDstComplexType getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkSrcDstComplexType }
     *     
     */
    public void setSource(NetworkSrcDstComplexType value) {
        this.source = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkSrcDstComplexType }
     *     
     */
    public NetworkSrcDstComplexType getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkSrcDstComplexType }
     *     
     */
    public void setDestination(NetworkSrcDstComplexType value) {
        this.destination = value;
    }

    /**
     * Gets the value of the processName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessName() {
        return processName;
    }

    /**
     * Sets the value of the processName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessName(String value) {
        this.processName = value;
    }

    /**
     * Gets the value of the payload property.
     * 
     * @return
     *     possible object is
     *     {@link MultiObjectComplexType }
     *     
     */
    public MultiObjectComplexType getPayload() {
        return payload;
    }

    /**
     * Sets the value of the payload property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiObjectComplexType }
     *     
     */
    public void setPayload(MultiObjectComplexType value) {
        this.payload = value;
    }

    /**
     * Gets the value of the rule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRule() {
        return rule;
    }

    /**
     * Sets the value of the rule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRule(String value) {
        this.rule = value;
    }

}
