//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.25 at 03:35:00 PM BST 
//


package event_logging._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseObjectComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseObjectComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{event-logging:3}BaseObjectGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseObjectComplexType", propOrder = {
    "meta",
    "type",
    "id",
    "name",
    "description",
    "classification",
    "state",
    "groups",
    "permissions",
    "tags"
})
@XmlSeeAlso({
    SearchResultComplexType.class,
    BannerComplexType.class,
    SearchResultsComplexType.class,
    VirtualSessionComplexType.class,
    ConfigurationComplexType.class,
    GroupComplexType.class,
    BaseChatComplexType.class,
    CriteriaComplexType.class,
    AssociationComplexType.class,
    VOIPComplexType.class,
    BaseFileComplexType.class,
    DocumentComplexType.class,
    EmailComplexType.class,
    ResourceComplexType.class,
    ObjectComplexType.class,
    UserComplexType.class
})
public abstract class BaseObjectComplexType {

    @XmlElement(name = "Meta")
    protected List<AnyContentComplexType> meta;
    @XmlElement(name = "Type")
    protected String type;
    @XmlElement(name = "Id")
    protected String id;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Classification")
    protected ClassificationComplexType classification;
    @XmlElement(name = "State")
    protected String state;
    @XmlElement(name = "Groups")
    protected GroupsComplexType groups;
    @XmlElement(name = "Permissions")
    protected BaseObjectComplexType.Permissions permissions;
    @XmlElement(name = "Tags")
    protected BaseObjectComplexType.Tags tags;

    /**
     * Gets the value of the meta property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the meta property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeta().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnyContentComplexType }
     * 
     * 
     */
    public List<AnyContentComplexType> getMeta() {
        if (meta == null) {
            meta = new ArrayList<AnyContentComplexType>();
        }
        return this.meta;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the classification property.
     * 
     * @return
     *     possible object is
     *     {@link ClassificationComplexType }
     *     
     */
    public ClassificationComplexType getClassification() {
        return classification;
    }

    /**
     * Sets the value of the classification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassificationComplexType }
     *     
     */
    public void setClassification(ClassificationComplexType value) {
        this.classification = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the groups property.
     * 
     * @return
     *     possible object is
     *     {@link GroupsComplexType }
     *     
     */
    public GroupsComplexType getGroups() {
        return groups;
    }

    /**
     * Sets the value of the groups property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupsComplexType }
     *     
     */
    public void setGroups(GroupsComplexType value) {
        this.groups = value;
    }

    /**
     * Gets the value of the permissions property.
     * 
     * @return
     *     possible object is
     *     {@link BaseObjectComplexType.Permissions }
     *     
     */
    public BaseObjectComplexType.Permissions getPermissions() {
        return permissions;
    }

    /**
     * Sets the value of the permissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseObjectComplexType.Permissions }
     *     
     */
    public void setPermissions(BaseObjectComplexType.Permissions value) {
        this.permissions = value;
    }

    /**
     * Gets the value of the tags property.
     * 
     * @return
     *     possible object is
     *     {@link BaseObjectComplexType.Tags }
     *     
     */
    public BaseObjectComplexType.Tags getTags() {
        return tags;
    }

    /**
     * Sets the value of the tags property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseObjectComplexType.Tags }
     *     
     */
    public void setTags(BaseObjectComplexType.Tags value) {
        this.tags = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Permission" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;choice>
     *                     &lt;element name="User" type="{event-logging:3}UserComplexType"/>
     *                     &lt;element name="Group" type="{event-logging:3}GroupComplexType"/>
     *                   &lt;/choice>
     *                   &lt;element name="Allow" type="{event-logging:3}PermissionAttributeSimpleType" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="Deny" type="{event-logging:3}PermissionAttributeSimpleType" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "permission"
    })
    public static class Permissions {

        @XmlElement(name = "Permission", required = true)
        protected List<BaseObjectComplexType.Permissions.Permission> permission;

        /**
         * Gets the value of the permission property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the permission property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPermission().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BaseObjectComplexType.Permissions.Permission }
         * 
         * 
         */
        public List<BaseObjectComplexType.Permissions.Permission> getPermission() {
            if (permission == null) {
                permission = new ArrayList<BaseObjectComplexType.Permissions.Permission>();
            }
            return this.permission;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;choice>
         *           &lt;element name="User" type="{event-logging:3}UserComplexType"/>
         *           &lt;element name="Group" type="{event-logging:3}GroupComplexType"/>
         *         &lt;/choice>
         *         &lt;element name="Allow" type="{event-logging:3}PermissionAttributeSimpleType" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="Deny" type="{event-logging:3}PermissionAttributeSimpleType" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "user",
            "group",
            "allow",
            "deny"
        })
        public static class Permission {

            @XmlElement(name = "User")
            protected UserComplexType user;
            @XmlElement(name = "Group")
            protected GroupComplexType group;
            @XmlElement(name = "Allow")
            @XmlSchemaType(name = "string")
            protected List<PermissionAttributeSimpleType> allow;
            @XmlElement(name = "Deny")
            @XmlSchemaType(name = "string")
            protected List<PermissionAttributeSimpleType> deny;

            /**
             * Gets the value of the user property.
             * 
             * @return
             *     possible object is
             *     {@link UserComplexType }
             *     
             */
            public UserComplexType getUser() {
                return user;
            }

            /**
             * Sets the value of the user property.
             * 
             * @param value
             *     allowed object is
             *     {@link UserComplexType }
             *     
             */
            public void setUser(UserComplexType value) {
                this.user = value;
            }

            /**
             * Gets the value of the group property.
             * 
             * @return
             *     possible object is
             *     {@link GroupComplexType }
             *     
             */
            public GroupComplexType getGroup() {
                return group;
            }

            /**
             * Sets the value of the group property.
             * 
             * @param value
             *     allowed object is
             *     {@link GroupComplexType }
             *     
             */
            public void setGroup(GroupComplexType value) {
                this.group = value;
            }

            /**
             * Gets the value of the allow property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the allow property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAllow().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link PermissionAttributeSimpleType }
             * 
             * 
             */
            public List<PermissionAttributeSimpleType> getAllow() {
                if (allow == null) {
                    allow = new ArrayList<PermissionAttributeSimpleType>();
                }
                return this.allow;
            }

            /**
             * Gets the value of the deny property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the deny property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDeny().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link PermissionAttributeSimpleType }
             * 
             * 
             */
            public List<PermissionAttributeSimpleType> getDeny() {
                if (deny == null) {
                    deny = new ArrayList<PermissionAttributeSimpleType>();
                }
                return this.deny;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Tag" type="{event-logging:3}TagSimpleType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tag"
    })
    public static class Tags {

        @XmlElement(name = "Tag", required = true)
        protected List<String> tag;

        /**
         * Gets the value of the tag property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tag property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTag().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getTag() {
            if (tag == null) {
                tag = new ArrayList<String>();
            }
            return this.tag;
        }

    }

}
