//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.25 at 03:35:00 PM BST 
//


package event_logging._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseAdvancedQueryOperatorComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseAdvancedQueryOperatorComplexType">
 *   &lt;complexContent>
 *     &lt;extension base="{event-logging:3}BaseAdvancedQueryItemComplexType">
 *       &lt;group ref="{event-logging:3}AdvancedQueryOperatorGroup" maxOccurs="unbounded" minOccurs="0"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseAdvancedQueryOperatorComplexType", propOrder = {
    "advancedQueryOperatorGroup"
})
@XmlSeeAlso({
    BaseAdvancedQueryOperatorComplexType.And.class,
    BaseAdvancedQueryOperatorComplexType.Or.class,
    BaseAdvancedQueryOperatorComplexType.Not.class
})
public abstract class BaseAdvancedQueryOperatorComplexType
    extends BaseAdvancedQueryItemComplexType
{

    @XmlElements({
        @XmlElement(name = "Term", type = TermComplexType.class),
        @XmlElement(name = "And", type = BaseAdvancedQueryOperatorComplexType.And.class),
        @XmlElement(name = "Or", type = BaseAdvancedQueryOperatorComplexType.Or.class),
        @XmlElement(name = "Not", type = BaseAdvancedQueryOperatorComplexType.Not.class)
    })
    protected List<BaseAdvancedQueryItemComplexType> advancedQueryOperatorGroup;

    /**
     * Gets the value of the advancedQueryOperatorGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the advancedQueryOperatorGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdvancedQueryOperatorGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TermComplexType }
     * {@link BaseAdvancedQueryOperatorComplexType.And }
     * {@link BaseAdvancedQueryOperatorComplexType.Or }
     * {@link BaseAdvancedQueryOperatorComplexType.Not }
     * 
     * 
     */
    public List<BaseAdvancedQueryItemComplexType> getAdvancedQueryOperatorGroup() {
        if (advancedQueryOperatorGroup == null) {
            advancedQueryOperatorGroup = new ArrayList<BaseAdvancedQueryItemComplexType>();
        }
        return this.advancedQueryOperatorGroup;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{event-logging:3}BaseAdvancedQueryOperatorComplexType">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class And
        extends BaseAdvancedQueryOperatorComplexType
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{event-logging:3}BaseAdvancedQueryOperatorComplexType">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Not
        extends BaseAdvancedQueryOperatorComplexType
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{event-logging:3}BaseAdvancedQueryOperatorComplexType">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Or
        extends BaseAdvancedQueryOperatorComplexType
    {


    }

}
