//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.25 at 03:35:00 PM BST 
//


package event_logging._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChangeActionSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ChangeActionSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="StartScan"/>
 *     &lt;enumeration value="StopScan"/>
 *     &lt;enumeration value="FileAdded"/>
 *     &lt;enumeration value="FileRemoved"/>
 *     &lt;enumeration value="FileModified"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ChangeActionSimpleType")
@XmlEnum
public enum ChangeActionSimpleType {

    @XmlEnumValue("StartScan")
    START_SCAN("StartScan"),
    @XmlEnumValue("StopScan")
    STOP_SCAN("StopScan"),
    @XmlEnumValue("FileAdded")
    FILE_ADDED("FileAdded"),
    @XmlEnumValue("FileRemoved")
    FILE_REMOVED("FileRemoved"),
    @XmlEnumValue("FileModified")
    FILE_MODIFIED("FileModified");
    private final String value;

    ChangeActionSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ChangeActionSimpleType fromValue(String v) {
        for (ChangeActionSimpleType c: ChangeActionSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
