//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.25 at 03:35:00 PM BST 
//


package event_logging._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CopyMoveOutcomeReasonSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CopyMoveOutcomeReasonSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DeviceFull"/>
 *     &lt;enumeration value="IOError"/>
 *     &lt;enumeration value="InvalidPath"/>
 *     &lt;enumeration value="PermissionDenied"/>
 *     &lt;enumeration value="ReadOnly"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CopyMoveOutcomeReasonSimpleType")
@XmlEnum
public enum CopyMoveOutcomeReasonSimpleType {

    @XmlEnumValue("DeviceFull")
    DEVICE_FULL("DeviceFull"),
    @XmlEnumValue("IOError")
    IO_ERROR("IOError"),
    @XmlEnumValue("InvalidPath")
    INVALID_PATH("InvalidPath"),
    @XmlEnumValue("PermissionDenied")
    PERMISSION_DENIED("PermissionDenied"),
    @XmlEnumValue("ReadOnly")
    READ_ONLY("ReadOnly");
    private final String value;

    CopyMoveOutcomeReasonSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CopyMoveOutcomeReasonSimpleType fromValue(String v) {
        for (CopyMoveOutcomeReasonSimpleType c: CopyMoveOutcomeReasonSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
