//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.25 at 03:35:00 PM BST 
//


package event_logging._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HardwareTypeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HardwareTypeSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="OpticalDrive"/>
 *     &lt;enumeration value="HardDisk"/>
 *     &lt;enumeration value="USBMassStorage"/>
 *     &lt;enumeration value="Printer"/>
 *     &lt;enumeration value="Modem"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HardwareTypeSimpleType")
@XmlEnum
public enum HardwareTypeSimpleType {

    @XmlEnumValue("OpticalDrive")
    OPTICAL_DRIVE("OpticalDrive"),
    @XmlEnumValue("HardDisk")
    HARD_DISK("HardDisk"),
    @XmlEnumValue("USBMassStorage")
    USB_MASS_STORAGE("USBMassStorage"),
    @XmlEnumValue("Printer")
    PRINTER("Printer"),
    @XmlEnumValue("Modem")
    MODEM("Modem"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    HardwareTypeSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HardwareTypeSimpleType fromValue(String v) {
        for (HardwareTypeSimpleType c: HardwareTypeSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
