//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.25 at 03:35:00 PM BST 
//


package event_logging._3;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the event_logging._3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: event_logging._3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Events }
     * 
     */
    public Events createEvents() {
        return new Events();
    }

    /**
     * Create an instance of {@link event_logging._3.BaseObjectComplexType.Permissions }
     * 
     */
    public event_logging._3.BaseObjectComplexType.Permissions createBaseObjectComplexTypePermissions() {
        return new event_logging._3.BaseObjectComplexType.Permissions();
    }

    /**
     * Create an instance of {@link AntiMalwareThreatComplexType }
     * 
     */
    public AntiMalwareThreatComplexType createAntiMalwareThreatComplexType() {
        return new AntiMalwareThreatComplexType();
    }

    /**
     * Create an instance of {@link SendReceiveComplexType }
     * 
     */
    public SendReceiveComplexType createSendReceiveComplexType() {
        return new SendReceiveComplexType();
    }

    /**
     * Create an instance of {@link SearchComplexType }
     * 
     */
    public SearchComplexType createSearchComplexType() {
        return new SearchComplexType();
    }

    /**
     * Create an instance of {@link ApprovalComplexType }
     * 
     */
    public ApprovalComplexType createApprovalComplexType() {
        return new ApprovalComplexType();
    }

    /**
     * Create an instance of {@link PurposeComplexType }
     * 
     */
    public PurposeComplexType createPurposeComplexType() {
        return new PurposeComplexType();
    }

    /**
     * Create an instance of {@link PurposeComplexType.Authorisations }
     * 
     */
    public PurposeComplexType.Authorisations createPurposeComplexTypeAuthorisations() {
        return new PurposeComplexType.Authorisations();
    }

    /**
     * Create an instance of {@link SystemComplexType }
     * 
     */
    public SystemComplexType createSystemComplexType() {
        return new SystemComplexType();
    }

    /**
     * Create an instance of {@link ClassificationComplexType }
     * 
     */
    public ClassificationComplexType createClassificationComplexType() {
        return new ClassificationComplexType();
    }

    /**
     * Create an instance of {@link QueryComplexType }
     * 
     */
    public QueryComplexType createQueryComplexType() {
        return new QueryComplexType();
    }

    /**
     * Create an instance of {@link Events.Event }
     * 
     */
    public Events.Event createEventsEvent() {
        return new Events.Event();
    }

    /**
     * Create an instance of {@link Events.Event.EventDetail }
     * 
     */
    public Events.Event.EventDetail createEventsEventEventDetail() {
        return new Events.Event.EventDetail();
    }

    /**
     * Create an instance of {@link Events.Event.EventDetail.Alert }
     * 
     */
    public Events.Event.EventDetail.Alert createEventsEventEventDetailAlert() {
        return new Events.Event.EventDetail.Alert();
    }

    /**
     * Create an instance of {@link Events.Event.EventDetail.Print }
     * 
     */
    public Events.Event.EventDetail.Print createEventsEventEventDetailPrint() {
        return new Events.Event.EventDetail.Print();
    }

    /**
     * Create an instance of {@link Events.Event.EventDetail.Authorise }
     * 
     */
    public Events.Event.EventDetail.Authorise createEventsEventEventDetailAuthorise() {
        return new Events.Event.EventDetail.Authorise();
    }

    /**
     * Create an instance of {@link Events.Event.EventSource }
     * 
     */
    public Events.Event.EventSource createEventsEventEventSource() {
        return new Events.Event.EventSource();
    }

    /**
     * Create an instance of {@link Events.Event.EventSource.Door }
     * 
     */
    public Events.Event.EventSource.Door createEventsEventEventSourceDoor() {
        return new Events.Event.EventSource.Door();
    }

    /**
     * Create an instance of {@link SearchResultComplexType }
     * 
     */
    public SearchResultComplexType createSearchResultComplexType() {
        return new SearchResultComplexType();
    }

    /**
     * Create an instance of {@link ShortcutComplexType }
     * 
     */
    public ShortcutComplexType createShortcutComplexType() {
        return new ShortcutComplexType();
    }

    /**
     * Create an instance of {@link AnyContentComplexType }
     * 
     */
    public AnyContentComplexType createAnyContentComplexType() {
        return new AnyContentComplexType();
    }

    /**
     * Create an instance of {@link AccessControlGroupsComplexType }
     * 
     */
    public AccessControlGroupsComplexType createAccessControlGroupsComplexType() {
        return new AccessControlGroupsComplexType();
    }

    /**
     * Create an instance of {@link GroupChatComplexType }
     * 
     */
    public GroupChatComplexType createGroupChatComplexType() {
        return new GroupChatComplexType();
    }

    /**
     * Create an instance of {@link SoftwareComplexType }
     * 
     */
    public SoftwareComplexType createSoftwareComplexType() {
        return new SoftwareComplexType();
    }

    /**
     * Create an instance of {@link MediaComplexType }
     * 
     */
    public MediaComplexType createMediaComplexType() {
        return new MediaComplexType();
    }

    /**
     * Create an instance of {@link BannerComplexType }
     * 
     */
    public BannerComplexType createBannerComplexType() {
        return new BannerComplexType();
    }

    /**
     * Create an instance of {@link SearchResultsComplexType }
     * 
     */
    public SearchResultsComplexType createSearchResultsComplexType() {
        return new SearchResultsComplexType();
    }

    /**
     * Create an instance of {@link NetworkSrcDstComplexType }
     * 
     */
    public NetworkSrcDstComplexType createNetworkSrcDstComplexType() {
        return new NetworkSrcDstComplexType();
    }

    /**
     * Create an instance of {@link VirtualSessionComplexType }
     * 
     */
    public VirtualSessionComplexType createVirtualSessionComplexType() {
        return new VirtualSessionComplexType();
    }

    /**
     * Create an instance of {@link LocationComplexType }
     * 
     */
    public LocationComplexType createLocationComplexType() {
        return new LocationComplexType();
    }

    /**
     * Create an instance of {@link ConfigurationComplexType }
     * 
     */
    public ConfigurationComplexType createConfigurationComplexType() {
        return new ConfigurationComplexType();
    }

    /**
     * Create an instance of {@link ObjectOutcomeComplexType }
     * 
     */
    public ObjectOutcomeComplexType createObjectOutcomeComplexType() {
        return new ObjectOutcomeComplexType();
    }

    /**
     * Create an instance of {@link FileComplexType }
     * 
     */
    public FileComplexType createFileComplexType() {
        return new FileComplexType();
    }

    /**
     * Create an instance of {@link ImportComplexType }
     * 
     */
    public ImportComplexType createImportComplexType() {
        return new ImportComplexType();
    }

    /**
     * Create an instance of {@link DeviceComplexType }
     * 
     */
    public DeviceComplexType createDeviceComplexType() {
        return new DeviceComplexType();
    }

    /**
     * Create an instance of {@link AntiMalwareComplexType }
     * 
     */
    public AntiMalwareComplexType createAntiMalwareComplexType() {
        return new AntiMalwareComplexType();
    }

    /**
     * Create an instance of {@link FromComplexType }
     * 
     */
    public FromComplexType createFromComplexType() {
        return new FromComplexType();
    }

    /**
     * Create an instance of {@link GroupComplexType }
     * 
     */
    public GroupComplexType createGroupComplexType() {
        return new GroupComplexType();
    }

    /**
     * Create an instance of {@link AuthenticateOutcomeComplexType }
     * 
     */
    public AuthenticateOutcomeComplexType createAuthenticateOutcomeComplexType() {
        return new AuthenticateOutcomeComplexType();
    }

    /**
     * Create an instance of {@link ChatComplexType }
     * 
     */
    public ChatComplexType createChatComplexType() {
        return new ChatComplexType();
    }

    /**
     * Create an instance of {@link HardwareComplexType }
     * 
     */
    public HardwareComplexType createHardwareComplexType() {
        return new HardwareComplexType();
    }

    /**
     * Create an instance of {@link GroupsComplexType }
     * 
     */
    public GroupsComplexType createGroupsComplexType() {
        return new GroupsComplexType();
    }

    /**
     * Create an instance of {@link CoordinatesComplexType }
     * 
     */
    public CoordinatesComplexType createCoordinatesComplexType() {
        return new CoordinatesComplexType();
    }

    /**
     * Create an instance of {@link OutcomeComplexType }
     * 
     */
    public OutcomeComplexType createOutcomeComplexType() {
        return new OutcomeComplexType();
    }

    /**
     * Create an instance of {@link CriteriaComplexType }
     * 
     */
    public CriteriaComplexType createCriteriaComplexType() {
        return new CriteriaComplexType();
    }

    /**
     * Create an instance of {@link OrganisationComplexType }
     * 
     */
    public OrganisationComplexType createOrganisationComplexType() {
        return new OrganisationComplexType();
    }

    /**
     * Create an instance of {@link NetworkOutcomeComplexType }
     * 
     */
    public NetworkOutcomeComplexType createNetworkOutcomeComplexType() {
        return new NetworkOutcomeComplexType();
    }

    /**
     * Create an instance of {@link UserDetailsComplexType }
     * 
     */
    public UserDetailsComplexType createUserDetailsComplexType() {
        return new UserDetailsComplexType();
    }

    /**
     * Create an instance of {@link TermComplexType }
     * 
     */
    public TermComplexType createTermComplexType() {
        return new TermComplexType();
    }

    /**
     * Create an instance of {@link AssociationComplexType }
     * 
     */
    public AssociationComplexType createAssociationComplexType() {
        return new AssociationComplexType();
    }

    /**
     * Create an instance of {@link VOIPComplexType }
     * 
     */
    public VOIPComplexType createVOIPComplexType() {
        return new VOIPComplexType();
    }

    /**
     * Create an instance of {@link FolderComplexType }
     * 
     */
    public FolderComplexType createFolderComplexType() {
        return new FolderComplexType();
    }

    /**
     * Create an instance of {@link ExportComplexType }
     * 
     */
    public ExportComplexType createExportComplexType() {
        return new ExportComplexType();
    }

    /**
     * Create an instance of {@link ActivityComplexType }
     * 
     */
    public ActivityComplexType createActivityComplexType() {
        return new ActivityComplexType();
    }

    /**
     * Create an instance of {@link DocumentComplexType }
     * 
     */
    public DocumentComplexType createDocumentComplexType() {
        return new DocumentComplexType();
    }

    /**
     * Create an instance of {@link MultiObjectComplexType }
     * 
     */
    public MultiObjectComplexType createMultiObjectComplexType() {
        return new MultiObjectComplexType();
    }

    /**
     * Create an instance of {@link EmailComplexType }
     * 
     */
    public EmailComplexType createEmailComplexType() {
        return new EmailComplexType();
    }

    /**
     * Create an instance of {@link InstallComplexType }
     * 
     */
    public InstallComplexType createInstallComplexType() {
        return new InstallComplexType();
    }

    /**
     * Create an instance of {@link ResourceComplexType }
     * 
     */
    public ResourceComplexType createResourceComplexType() {
        return new ResourceComplexType();
    }

    /**
     * Create an instance of {@link CopyMoveComplexType }
     * 
     */
    public CopyMoveComplexType createCopyMoveComplexType() {
        return new CopyMoveComplexType();
    }

    /**
     * Create an instance of {@link CopyMoveOutcomeComplexType }
     * 
     */
    public CopyMoveOutcomeComplexType createCopyMoveOutcomeComplexType() {
        return new CopyMoveOutcomeComplexType();
    }

    /**
     * Create an instance of {@link ProductComplexType }
     * 
     */
    public ProductComplexType createProductComplexType() {
        return new ProductComplexType();
    }

    /**
     * Create an instance of {@link NetworkComplexType }
     * 
     */
    public NetworkComplexType createNetworkComplexType() {
        return new NetworkComplexType();
    }

    /**
     * Create an instance of {@link ObjectComplexType }
     * 
     */
    public ObjectComplexType createObjectComplexType() {
        return new ObjectComplexType();
    }

    /**
     * Create an instance of {@link DataComplexType }
     * 
     */
    public DataComplexType createDataComplexType() {
        return new DataComplexType();
    }

    /**
     * Create an instance of {@link UserComplexType }
     * 
     */
    public UserComplexType createUserComplexType() {
        return new UserComplexType();
    }

    /**
     * Create an instance of {@link event_logging._3.BaseObjectComplexType.Tags }
     * 
     */
    public event_logging._3.BaseObjectComplexType.Tags createBaseObjectComplexTypeTags() {
        return new event_logging._3.BaseObjectComplexType.Tags();
    }

    /**
     * Create an instance of {@link event_logging._3.BaseObjectComplexType.Permissions.Permission }
     * 
     */
    public event_logging._3.BaseObjectComplexType.Permissions.Permission createBaseObjectComplexTypePermissionsPermission() {
        return new event_logging._3.BaseObjectComplexType.Permissions.Permission();
    }

    /**
     * Create an instance of {@link event_logging._3.BaseOutcomeComplexType.AuthService }
     * 
     */
    public event_logging._3.BaseOutcomeComplexType.AuthService createBaseOutcomeComplexTypeAuthService() {
        return new event_logging._3.BaseOutcomeComplexType.AuthService();
    }

    /**
     * Create an instance of {@link event_logging._3.BaseAntiMalwareComplexType.Signature }
     * 
     */
    public event_logging._3.BaseAntiMalwareComplexType.Signature createBaseAntiMalwareComplexTypeSignature() {
        return new event_logging._3.BaseAntiMalwareComplexType.Signature();
    }

    /**
     * Create an instance of {@link AntiMalwareThreatComplexType.Threat }
     * 
     */
    public AntiMalwareThreatComplexType.Threat createAntiMalwareThreatComplexTypeThreat() {
        return new AntiMalwareThreatComplexType.Threat();
    }

    /**
     * Create an instance of {@link SendReceiveComplexType.Source }
     * 
     */
    public SendReceiveComplexType.Source createSendReceiveComplexTypeSource() {
        return new SendReceiveComplexType.Source();
    }

    /**
     * Create an instance of {@link SendReceiveComplexType.Destination }
     * 
     */
    public SendReceiveComplexType.Destination createSendReceiveComplexTypeDestination() {
        return new SendReceiveComplexType.Destination();
    }

    /**
     * Create an instance of {@link SearchComplexType.DataSources }
     * 
     */
    public SearchComplexType.DataSources createSearchComplexTypeDataSources() {
        return new SearchComplexType.DataSources();
    }

    /**
     * Create an instance of {@link SearchComplexType.ResultPage }
     * 
     */
    public SearchComplexType.ResultPage createSearchComplexTypeResultPage() {
        return new SearchComplexType.ResultPage();
    }

    /**
     * Create an instance of {@link event_logging._3.BaseFileComplexType.Hash }
     * 
     */
    public event_logging._3.BaseFileComplexType.Hash createBaseFileComplexTypeHash() {
        return new event_logging._3.BaseFileComplexType.Hash();
    }

    /**
     * Create an instance of {@link ApprovalComplexType.Requestors }
     * 
     */
    public ApprovalComplexType.Requestors createApprovalComplexTypeRequestors() {
        return new ApprovalComplexType.Requestors();
    }

    /**
     * Create an instance of {@link ApprovalComplexType.Approvers }
     * 
     */
    public ApprovalComplexType.Approvers createApprovalComplexTypeApprovers() {
        return new ApprovalComplexType.Approvers();
    }

    /**
     * Create an instance of {@link PurposeComplexType.Authorisations.Auth }
     * 
     */
    public PurposeComplexType.Authorisations.Auth createPurposeComplexTypeAuthorisationsAuth() {
        return new PurposeComplexType.Authorisations.Auth();
    }

    /**
     * Create an instance of {@link SystemComplexType.Tags }
     * 
     */
    public SystemComplexType.Tags createSystemComplexTypeTags() {
        return new SystemComplexType.Tags();
    }

    /**
     * Create an instance of {@link ClassificationComplexType.Descriptors }
     * 
     */
    public ClassificationComplexType.Descriptors createClassificationComplexTypeDescriptors() {
        return new ClassificationComplexType.Descriptors();
    }

    /**
     * Create an instance of {@link ClassificationComplexType.PermittedNationalities }
     * 
     */
    public ClassificationComplexType.PermittedNationalities createClassificationComplexTypePermittedNationalities() {
        return new ClassificationComplexType.PermittedNationalities();
    }

    /**
     * Create an instance of {@link ClassificationComplexType.PermittedOrganisations }
     * 
     */
    public ClassificationComplexType.PermittedOrganisations createClassificationComplexTypePermittedOrganisations() {
        return new ClassificationComplexType.PermittedOrganisations();
    }

    /**
     * Create an instance of {@link ClassificationComplexType.DisseminationControls }
     * 
     */
    public ClassificationComplexType.DisseminationControls createClassificationComplexTypeDisseminationControls() {
        return new ClassificationComplexType.DisseminationControls();
    }

    /**
     * Create an instance of {@link ClassificationComplexType.Disposition }
     * 
     */
    public ClassificationComplexType.Disposition createClassificationComplexTypeDisposition() {
        return new ClassificationComplexType.Disposition();
    }

    /**
     * Create an instance of {@link event_logging._3.BaseAdvancedQueryOperatorComplexType.And }
     * 
     */
    public event_logging._3.BaseAdvancedQueryOperatorComplexType.And createBaseAdvancedQueryOperatorComplexTypeAnd() {
        return new event_logging._3.BaseAdvancedQueryOperatorComplexType.And();
    }

    /**
     * Create an instance of {@link event_logging._3.BaseAdvancedQueryOperatorComplexType.Or }
     * 
     */
    public event_logging._3.BaseAdvancedQueryOperatorComplexType.Or createBaseAdvancedQueryOperatorComplexTypeOr() {
        return new event_logging._3.BaseAdvancedQueryOperatorComplexType.Or();
    }

    /**
     * Create an instance of {@link event_logging._3.BaseAdvancedQueryOperatorComplexType.Not }
     * 
     */
    public event_logging._3.BaseAdvancedQueryOperatorComplexType.Not createBaseAdvancedQueryOperatorComplexTypeNot() {
        return new event_logging._3.BaseAdvancedQueryOperatorComplexType.Not();
    }

    /**
     * Create an instance of {@link QueryComplexType.Advanced }
     * 
     */
    public QueryComplexType.Advanced createQueryComplexTypeAdvanced() {
        return new QueryComplexType.Advanced();
    }

    /**
     * Create an instance of {@link QueryComplexType.Simple }
     * 
     */
    public QueryComplexType.Simple createQueryComplexTypeSimple() {
        return new QueryComplexType.Simple();
    }

    /**
     * Create an instance of {@link Events.Event.EventTime }
     * 
     */
    public Events.Event.EventTime createEventsEventEventTime() {
        return new Events.Event.EventTime();
    }

    /**
     * Create an instance of {@link Events.Event.EventChain }
     * 
     */
    public Events.Event.EventChain createEventsEventEventChain() {
        return new Events.Event.EventChain();
    }

    /**
     * Create an instance of {@link Events.Event.EventDetail.Authenticate }
     * 
     */
    public Events.Event.EventDetail.Authenticate createEventsEventEventDetailAuthenticate() {
        return new Events.Event.EventDetail.Authenticate();
    }

    /**
     * Create an instance of {@link Events.Event.EventDetail.Update }
     * 
     */
    public Events.Event.EventDetail.Update createEventsEventEventDetailUpdate() {
        return new Events.Event.EventDetail.Update();
    }

    /**
     * Create an instance of {@link Events.Event.EventDetail.Process }
     * 
     */
    public Events.Event.EventDetail.Process createEventsEventEventDetailProcess() {
        return new Events.Event.EventDetail.Process();
    }

    /**
     * Create an instance of {@link Events.Event.EventDetail.Network }
     * 
     */
    public Events.Event.EventDetail.Network createEventsEventEventDetailNetwork() {
        return new Events.Event.EventDetail.Network();
    }

    /**
     * Create an instance of {@link Events.Event.EventDetail.AntiMalware }
     * 
     */
    public Events.Event.EventDetail.AntiMalware createEventsEventEventDetailAntiMalware() {
        return new Events.Event.EventDetail.AntiMalware();
    }

    /**
     * Create an instance of {@link Events.Event.EventDetail.Unknown }
     * 
     */
    public Events.Event.EventDetail.Unknown createEventsEventEventDetailUnknown() {
        return new Events.Event.EventDetail.Unknown();
    }

    /**
     * Create an instance of {@link Events.Event.EventDetail.Alert.IDS }
     * 
     */
    public Events.Event.EventDetail.Alert.IDS createEventsEventEventDetailAlertIDS() {
        return new Events.Event.EventDetail.Alert.IDS();
    }

    /**
     * Create an instance of {@link Events.Event.EventDetail.Alert.Change }
     * 
     */
    public Events.Event.EventDetail.Alert.Change createEventsEventEventDetailAlertChange() {
        return new Events.Event.EventDetail.Alert.Change();
    }

    /**
     * Create an instance of {@link Events.Event.EventDetail.Print.PrintJob }
     * 
     */
    public Events.Event.EventDetail.Print.PrintJob createEventsEventEventDetailPrintPrintJob() {
        return new Events.Event.EventDetail.Print.PrintJob();
    }

    /**
     * Create an instance of {@link Events.Event.EventDetail.Print.PrintSettings }
     * 
     */
    public Events.Event.EventDetail.Print.PrintSettings createEventsEventEventDetailPrintPrintSettings() {
        return new Events.Event.EventDetail.Print.PrintSettings();
    }

    /**
     * Create an instance of {@link Events.Event.EventDetail.Authorise.AddGroups }
     * 
     */
    public Events.Event.EventDetail.Authorise.AddGroups createEventsEventEventDetailAuthoriseAddGroups() {
        return new Events.Event.EventDetail.Authorise.AddGroups();
    }

    /**
     * Create an instance of {@link Events.Event.EventDetail.Authorise.RemoveGroups }
     * 
     */
    public Events.Event.EventDetail.Authorise.RemoveGroups createEventsEventEventDetailAuthoriseRemoveGroups() {
        return new Events.Event.EventDetail.Authorise.RemoveGroups();
    }

    /**
     * Create an instance of {@link Events.Event.EventSource.Door.AddAccess }
     * 
     */
    public Events.Event.EventSource.Door.AddAccess createEventsEventEventSourceDoorAddAccess() {
        return new Events.Event.EventSource.Door.AddAccess();
    }

}
