//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.25 at 03:35:00 PM BST 
//


package event_logging._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrintActionSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PrintActionSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CreateJob"/>
 *     &lt;enumeration value="CancelJob"/>
 *     &lt;enumeration value="PauseJob"/>
 *     &lt;enumeration value="ResumeJob"/>
 *     &lt;enumeration value="StartPrint"/>
 *     &lt;enumeration value="FinishPrint"/>
 *     &lt;enumeration value="CancelPrint"/>
 *     &lt;enumeration value="FailedPrint"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PrintActionSimpleType")
@XmlEnum
public enum PrintActionSimpleType {

    @XmlEnumValue("CreateJob")
    CREATE_JOB("CreateJob"),
    @XmlEnumValue("CancelJob")
    CANCEL_JOB("CancelJob"),
    @XmlEnumValue("PauseJob")
    PAUSE_JOB("PauseJob"),
    @XmlEnumValue("ResumeJob")
    RESUME_JOB("ResumeJob"),
    @XmlEnumValue("StartPrint")
    START_PRINT("StartPrint"),
    @XmlEnumValue("FinishPrint")
    FINISH_PRINT("FinishPrint"),
    @XmlEnumValue("CancelPrint")
    CANCEL_PRINT("CancelPrint"),
    @XmlEnumValue("FailedPrint")
    FAILED_PRINT("FailedPrint"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    PrintActionSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PrintActionSimpleType fromValue(String v) {
        for (PrintActionSimpleType c: PrintActionSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
