//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.25 at 03:35:00 PM BST 
//


package event_logging._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrintSettingsOrientationSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PrintSettingsOrientationSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Portrait"/>
 *     &lt;enumeration value="Landscape"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PrintSettingsOrientationSimpleType")
@XmlEnum
public enum PrintSettingsOrientationSimpleType {

    @XmlEnumValue("Portrait")
    PORTRAIT("Portrait"),
    @XmlEnumValue("Landscape")
    LANDSCAPE("Landscape");
    private final String value;

    PrintSettingsOrientationSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PrintSettingsOrientationSimpleType fromValue(String v) {
        for (PrintSettingsOrientationSimpleType c: PrintSettingsOrientationSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
