//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.25 at 03:35:00 PM BST 
//


package event_logging._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QueryComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Advanced" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{event-logging:3}AdvancedQueryOperatorGroup" maxOccurs="unbounded" minOccurs="0"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Simple" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Include" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Exclude" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Raw" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryComplexType", propOrder = {
    "id",
    "name",
    "description",
    "advanced",
    "simple",
    "raw"
})
public class QueryComplexType {

    @XmlElement(name = "Id")
    protected String id;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Advanced")
    protected QueryComplexType.Advanced advanced;
    @XmlElement(name = "Simple")
    protected QueryComplexType.Simple simple;
    @XmlElement(name = "Raw")
    protected String raw;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the advanced property.
     * 
     * @return
     *     possible object is
     *     {@link QueryComplexType.Advanced }
     *     
     */
    public QueryComplexType.Advanced getAdvanced() {
        return advanced;
    }

    /**
     * Sets the value of the advanced property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryComplexType.Advanced }
     *     
     */
    public void setAdvanced(QueryComplexType.Advanced value) {
        this.advanced = value;
    }

    /**
     * Gets the value of the simple property.
     * 
     * @return
     *     possible object is
     *     {@link QueryComplexType.Simple }
     *     
     */
    public QueryComplexType.Simple getSimple() {
        return simple;
    }

    /**
     * Sets the value of the simple property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryComplexType.Simple }
     *     
     */
    public void setSimple(QueryComplexType.Simple value) {
        this.simple = value;
    }

    /**
     * Gets the value of the raw property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRaw() {
        return raw;
    }

    /**
     * Sets the value of the raw property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRaw(String value) {
        this.raw = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{event-logging:3}AdvancedQueryOperatorGroup" maxOccurs="unbounded" minOccurs="0"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "advancedQueryOperatorGroup"
    })
    public static class Advanced {

        @XmlElements({
            @XmlElement(name = "Term", type = TermComplexType.class),
            @XmlElement(name = "And", type = event_logging._3.BaseAdvancedQueryOperatorComplexType.And.class),
            @XmlElement(name = "Or", type = event_logging._3.BaseAdvancedQueryOperatorComplexType.Or.class),
            @XmlElement(name = "Not", type = event_logging._3.BaseAdvancedQueryOperatorComplexType.Not.class)
        })
        protected List<BaseAdvancedQueryItemComplexType> advancedQueryOperatorGroup;

        /**
         * Gets the value of the advancedQueryOperatorGroup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the advancedQueryOperatorGroup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAdvancedQueryOperatorGroup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TermComplexType }
         * {@link event_logging._3.BaseAdvancedQueryOperatorComplexType.And }
         * {@link event_logging._3.BaseAdvancedQueryOperatorComplexType.Or }
         * {@link event_logging._3.BaseAdvancedQueryOperatorComplexType.Not }
         * 
         * 
         */
        public List<BaseAdvancedQueryItemComplexType> getAdvancedQueryOperatorGroup() {
            if (advancedQueryOperatorGroup == null) {
                advancedQueryOperatorGroup = new ArrayList<BaseAdvancedQueryItemComplexType>();
            }
            return this.advancedQueryOperatorGroup;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Include" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Exclude" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "include",
        "exclude"
    })
    public static class Simple {

        @XmlElement(name = "Include")
        protected String include;
        @XmlElement(name = "Exclude")
        protected String exclude;

        /**
         * Gets the value of the include property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInclude() {
            return include;
        }

        /**
         * Sets the value of the include property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInclude(String value) {
            this.include = value;
        }

        /**
         * Gets the value of the exclude property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExclude() {
            return exclude;
        }

        /**
         * Sets the value of the exclude property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExclude(String value) {
            this.exclude = value;
        }

    }

}
