//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.25 at 03:35:00 PM BST 
//


package event_logging._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TermConditionSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TermConditionSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Exists"/>
 *     &lt;enumeration value="NotExists"/>
 *     &lt;enumeration value="Contains"/>
 *     &lt;enumeration value="NotContains"/>
 *     &lt;enumeration value="Empty"/>
 *     &lt;enumeration value="NotEmpty"/>
 *     &lt;enumeration value="Equals"/>
 *     &lt;enumeration value="NotEquals"/>
 *     &lt;enumeration value="GreaterThan"/>
 *     &lt;enumeration value="GreaterThanEqualTo"/>
 *     &lt;enumeration value="LessThan"/>
 *     &lt;enumeration value="LessThanEqualTo"/>
 *     &lt;enumeration value="StartsWith"/>
 *     &lt;enumeration value="NotStartsWith"/>
 *     &lt;enumeration value="Regex"/>
 *     &lt;enumeration value="NotRegex"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TermConditionSimpleType")
@XmlEnum
public enum TermConditionSimpleType {

    @XmlEnumValue("Exists")
    EXISTS("Exists"),
    @XmlEnumValue("NotExists")
    NOT_EXISTS("NotExists"),
    @XmlEnumValue("Contains")
    CONTAINS("Contains"),
    @XmlEnumValue("NotContains")
    NOT_CONTAINS("NotContains"),
    @XmlEnumValue("Empty")
    EMPTY("Empty"),
    @XmlEnumValue("NotEmpty")
    NOT_EMPTY("NotEmpty"),
    @XmlEnumValue("Equals")
    EQUALS("Equals"),
    @XmlEnumValue("NotEquals")
    NOT_EQUALS("NotEquals"),
    @XmlEnumValue("GreaterThan")
    GREATER_THAN("GreaterThan"),
    @XmlEnumValue("GreaterThanEqualTo")
    GREATER_THAN_EQUAL_TO("GreaterThanEqualTo"),
    @XmlEnumValue("LessThan")
    LESS_THAN("LessThan"),
    @XmlEnumValue("LessThanEqualTo")
    LESS_THAN_EQUAL_TO("LessThanEqualTo"),
    @XmlEnumValue("StartsWith")
    STARTS_WITH("StartsWith"),
    @XmlEnumValue("NotStartsWith")
    NOT_STARTS_WITH("NotStartsWith"),
    @XmlEnumValue("Regex")
    REGEX("Regex"),
    @XmlEnumValue("NotRegex")
    NOT_REGEX("NotRegex");
    private final String value;

    TermConditionSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TermConditionSimpleType fromValue(String v) {
        for (TermConditionSimpleType c: TermConditionSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
